"""Trivia question bank for Trivia Blitz — 200+ questions across many categories."""

TRIVIA_QUESTIONS: list[dict] = [
    # ── Geography ─────────────────────────────────────────────────────────────
    {"q": "What is the capital of France?", "options": ["London", "Paris", "Berlin", "Madrid"], "answer": 1},
    {"q": "What is the capital of Japan?", "options": ["Seoul", "Beijing", "Tokyo", "Bangkok"], "answer": 2},
    {"q": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": 2},
    {"q": "What is the capital of Canada?", "options": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": 2},
    {"q": "What is the capital of Italy?", "options": ["Milan", "Venice", "Rome", "Florence"], "answer": 2},
    {"q": "What is the capital of Egypt?", "options": ["Alexandria", "Cairo", "Giza", "Luxor"], "answer": 1},
    {"q": "What is the capital of Germany?", "options": ["Munich", "Hamburg", "Berlin", "Frankfurt"], "answer": 2},
    {"q": "What is the capital of Spain?", "options": ["Barcelona", "Madrid", "Seville", "Valencia"], "answer": 1},
    {"q": "What is the capital of Russia?", "options": ["St. Petersburg", "Moscow", "Kiev", "Warsaw"], "answer": 1},
    {"q": "What is the capital of India?", "options": ["Mumbai", "Kolkata", "New Delhi", "Chennai"], "answer": 2},
    {"q": "What is the capital of Brazil?", "options": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "answer": 2},
    {"q": "What is the capital of South Korea?", "options": ["Busan", "Seoul", "Incheon", "Daegu"], "answer": 1},
    {"q": "What is the capital of Mexico?", "options": ["Guadalajara", "Mexico City", "Monterrey", "Cancún"], "answer": 1},
    {"q": "What is the capital of Argentina?", "options": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"], "answer": 0},
    {"q": "What is the capital of Turkey?", "options": ["Istanbul", "Ankara", "Izmir", "Antalya"], "answer": 1},
    {"q": "What is the capital of Thailand?", "options": ["Phuket", "Bangkok", "Chiang Mai", "Pattaya"], "answer": 1},
    {"q": "What is the capital of Norway?", "options": ["Bergen", "Oslo", "Stockholm", "Copenhagen"], "answer": 1},
    {"q": "What is the capital of Greece?", "options": ["Thessaloniki", "Athens", "Sparta", "Crete"], "answer": 1},
    {"q": "What is the capital of Sweden?", "options": ["Oslo", "Helsinki", "Stockholm", "Gothenburg"], "answer": 2},
    {"q": "What is the capital of Poland?", "options": ["Kraków", "Warsaw", "Gdansk", "Poznan"], "answer": 1},
    {"q": "How many continents are there?", "options": ["5", "6", "7", "8"], "answer": 2},
    {"q": "What is the largest ocean on Earth?", "options": ["Atlantic", "Indian", "Pacific", "Arctic"], "answer": 2},
    {"q": "What is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "answer": 1},
    {"q": "What is the largest desert in the world?", "options": ["Gobi", "Sahara", "Antarctic", "Arabian"], "answer": 2},
    {"q": "Which country is home to the kangaroo?", "options": ["South Africa", "Australia", "Brazil", "India"], "answer": 1},
    {"q": "Which country has the most people?", "options": ["USA", "India", "China", "Indonesia"], "answer": 1},
    {"q": "What is the tallest mountain in the world?", "options": ["K2", "Everest", "Kilimanjaro", "Denali"], "answer": 1},
    {"q": "Which country invented paper?", "options": ["Japan", "Egypt", "China", "Greece"], "answer": 2},
    {"q": "What is the main language spoken in Brazil?", "options": ["Spanish", "Portuguese", "French", "Italian"], "answer": 1},
    {"q": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Japan", "Korea", "Thailand"], "answer": 1},
    {"q": "What is the smallest country in the world?", "options": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], "answer": 1},
    {"q": "Which ocean is the Bermuda Triangle located in?", "options": ["Pacific", "Indian", "Atlantic", "Arctic"], "answer": 2},
    {"q": "What country is the Eiffel Tower in?", "options": ["Italy", "France", "Belgium", "Spain"], "answer": 1},
    {"q": "What country is the Great Wall located in?", "options": ["Japan", "Korea", "China", "Mongolia"], "answer": 2},
    {"q": "Which US state is known as the Sunshine State?", "options": ["California", "Florida", "Texas", "Hawaii"], "answer": 1},
    {"q": "What is the largest country by land area?", "options": ["USA", "China", "Canada", "Russia"], "answer": 3},
    {"q": "Which sea separates Europe and Africa?", "options": ["Red Sea", "Mediterranean", "Black Sea", "Caspian"], "answer": 1},
    {"q": "What is the capital of Iceland?", "options": ["Oslo", "Reykjavik", "Helsinki", "Bergen"], "answer": 1},
    {"q": "Which African country was formerly called Abyssinia?", "options": ["Ethiopia", "Egypt", "Sudan", "Kenya"], "answer": 0},
    {"q": "What strait separates Alaska and Russia?", "options": ["Magellan", "Bering", "Hormuz", "Gibraltar"], "answer": 1},

    # ── Science ───────────────────────────────────────────────────────────────
    {"q": "What planet is known as the Red Planet?", "options": ["Venus", "Mars", "Jupiter", "Saturn"], "answer": 1},
    {"q": "Which planet is closest to the Sun?", "options": ["Venus", "Earth", "Mercury", "Mars"], "answer": 2},
    {"q": "Which planet has the most moons?", "options": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": 1},
    {"q": "What is the chemical symbol for gold?", "options": ["Go", "Gd", "Au", "Ag"], "answer": 2},
    {"q": "What is the chemical symbol for iron?", "options": ["Ir", "Fe", "In", "I"], "answer": 1},
    {"q": "What is the chemical symbol for silver?", "options": ["Si", "Sv", "Ag", "Au"], "answer": 2},
    {"q": "What gas do plants absorb from the air?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": 2},
    {"q": "Which element has the atomic number 1?", "options": ["Helium", "Hydrogen", "Oxygen", "Carbon"], "answer": 1},
    {"q": "What is H₂O commonly known as?", "options": ["Salt", "Water", "Air", "Sugar"], "answer": 1},
    {"q": "What is the hardest natural substance?", "options": ["Gold", "Iron", "Diamond", "Quartz"], "answer": 2},
    {"q": "What is the speed of light approximately (km/s)?", "options": ["150,000", "300,000", "450,000", "600,000"], "answer": 1},
    {"q": "Which organ pumps blood through the body?", "options": ["Brain", "Liver", "Heart", "Lungs"], "answer": 2},
    {"q": "What is the largest mammal?", "options": ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"], "answer": 1},
    {"q": "How many bones are in the adult human body?", "options": ["106", "206", "306", "406"], "answer": 1},
    {"q": "What is the center of an atom called?", "options": ["Electron", "Proton", "Nucleus", "Neutron"], "answer": 2},
    {"q": "What type of animal is a frog?", "options": ["Reptile", "Amphibian", "Mammal", "Fish"], "answer": 1},
    {"q": "What force keeps us on the ground?", "options": ["Magnetism", "Friction", "Gravity", "Inertia"], "answer": 2},
    {"q": "What is the boiling point of water (°C)?", "options": ["90", "100", "110", "120"], "answer": 1},
    {"q": "What planet is famous for its rings?", "options": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": 1},
    {"q": "What is the main gas in Earth's atmosphere?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "answer": 2},
    {"q": "What part of the cell contains DNA?", "options": ["Ribosome", "Nucleus", "Membrane", "Cytoplasm"], "answer": 1},
    {"q": "What is the nearest star to Earth?", "options": ["Proxima Centauri", "The Sun", "Sirius", "Alpha Centauri"], "answer": 1},
    {"q": "What vitamin do we get from sunlight?", "options": ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], "answer": 2},
    {"q": "What is the study of earthquakes called?", "options": ["Meteorology", "Seismology", "Geology", "Volcanology"], "answer": 1},
    {"q": "Which blood type is the universal donor?", "options": ["A", "B", "AB", "O negative"], "answer": 3},
    {"q": "What is the chemical formula for table salt?", "options": ["NaCl", "KCl", "CaCl", "MgCl"], "answer": 0},
    {"q": "What is the largest organ in the human body?", "options": ["Liver", "Brain", "Skin", "Heart"], "answer": 2},
    {"q": "What metal is liquid at room temperature?", "options": ["Lead", "Mercury", "Tin", "Zinc"], "answer": 1},
    {"q": "What is the powerhouse of the cell?", "options": ["Nucleus", "Mitochondria", "Ribosome", "Golgi body"], "answer": 1},
    {"q": "How many planets are in our solar system?", "options": ["7", "8", "9", "10"], "answer": 1},

    # ── History ───────────────────────────────────────────────────────────────
    {"q": "In what year did World War II end?", "options": ["1943", "1944", "1945", "1946"], "answer": 2},
    {"q": "Who was the first president of the USA?", "options": ["Lincoln", "Washington", "Jefferson", "Adams"], "answer": 1},
    {"q": "In what year did the Titanic sink?", "options": ["1905", "1912", "1918", "1923"], "answer": 1},
    {"q": "Who discovered penicillin?", "options": ["Pasteur", "Fleming", "Curie", "Edison"], "answer": 1},
    {"q": "The Berlin Wall fell in which year?", "options": ["1987", "1989", "1991", "1993"], "answer": 1},
    {"q": "Who was the first man on the Moon?", "options": ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], "answer": 1},
    {"q": "In what year did India gain independence?", "options": ["1945", "1947", "1950", "1952"], "answer": 1},
    {"q": "Who painted the ceiling of the Sistine Chapel?", "options": ["Da Vinci", "Raphael", "Michelangelo", "Donatello"], "answer": 2},
    {"q": "Ancient Egypt built which famous monuments?", "options": ["Colosseum", "Pyramids", "Parthenon", "Stonehenge"], "answer": 1},
    {"q": "Who wrote the Declaration of Independence?", "options": ["Washington", "Franklin", "Jefferson", "Hamilton"], "answer": 2},
    {"q": "The Roman Empire fell in which century?", "options": ["3rd", "4th", "5th", "6th"], "answer": 2},
    {"q": "Who was known as the Maid of Orléans?", "options": ["Cleopatra", "Joan of Arc", "Elizabeth I", "Catherine"], "answer": 1},
    {"q": "In which country did the Renaissance begin?", "options": ["France", "Italy", "England", "Greece"], "answer": 1},
    {"q": "Who invented the telephone?", "options": ["Edison", "Tesla", "Bell", "Marconi"], "answer": 2},
    {"q": "The Magna Carta was signed in which country?", "options": ["France", "England", "Scotland", "Germany"], "answer": 1},
    {"q": "Who was the leader of Nazi Germany?", "options": ["Stalin", "Hitler", "Mussolini", "Franco"], "answer": 1},
    {"q": "In what year did the French Revolution begin?", "options": ["1776", "1789", "1804", "1815"], "answer": 1},
    {"q": "Who built the Taj Mahal?", "options": ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], "answer": 1},
    {"q": "Which ship brought the Pilgrims to America?", "options": ["Santa Maria", "Mayflower", "Endeavour", "Victory"], "answer": 1},
    {"q": "Who was the first woman to win a Nobel Prize?", "options": ["Curie", "Franklin", "Hopper", "Nightingale"], "answer": 0},

    # ── Math ──────────────────────────────────────────────────────────────────
    {"q": "What is the smallest prime number?", "options": ["0", "1", "2", "3"], "answer": 2},
    {"q": "What is 15 × 15?", "options": ["125", "200", "225", "250"], "answer": 2},
    {"q": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"], "answer": 1},
    {"q": "What is the value of pi (approx)?", "options": ["2.14", "3.14", "4.14", "3.41"], "answer": 1},
    {"q": "What is 12 × 12?", "options": ["124", "144", "154", "164"], "answer": 1},
    {"q": "How many degrees in a right angle?", "options": ["45", "90", "180", "360"], "answer": 1},
    {"q": "What is the square root of 144?", "options": ["10", "11", "12", "13"], "answer": 2},
    {"q": "How many sides does an octagon have?", "options": ["6", "7", "8", "9"], "answer": 2},
    {"q": "What is 1000 ÷ 25?", "options": ["25", "30", "40", "50"], "answer": 2},
    {"q": "What is 7! (7 factorial)?", "options": ["720", "5040", "40320", "362880"], "answer": 1},
    {"q": "What is the sum of angles in a triangle?", "options": ["90°", "180°", "270°", "360°"], "answer": 1},
    {"q": "What is 2 to the power of 10?", "options": ["512", "1024", "2048", "4096"], "answer": 1},
    {"q": "How many millimeters in a centimeter?", "options": ["10", "100", "1000", "5"], "answer": 0},
    {"q": "What is 25% of 200?", "options": ["25", "50", "75", "100"], "answer": 1},
    {"q": "What is the next prime after 7?", "options": ["8", "9", "10", "11"], "answer": 3},

    # ── Literature & Arts ─────────────────────────────────────────────────────
    {"q": "Who painted the Mona Lisa?", "options": ["Van Gogh", "Picasso", "Da Vinci", "Rembrandt"], "answer": 2},
    {"q": "Who wrote Romeo and Juliet?", "options": ["Dickens", "Shakespeare", "Twain", "Austen"], "answer": 1},
    {"q": "Who wrote '1984'?", "options": ["Huxley", "Orwell", "Bradbury", "Asimov"], "answer": 1},
    {"q": "Who wrote 'Harry Potter'?", "options": ["Tolkien", "Rowling", "Lewis", "Martin"], "answer": 1},
    {"q": "Who painted 'Starry Night'?", "options": ["Monet", "Van Gogh", "Picasso", "Renoir"], "answer": 1},
    {"q": "Who wrote 'The Odyssey'?", "options": ["Virgil", "Homer", "Sophocles", "Plato"], "answer": 1},
    {"q": "Who wrote 'Pride and Prejudice'?", "options": ["Brontë", "Austen", "Eliot", "Woolf"], "answer": 1},
    {"q": "Who wrote 'The Great Gatsby'?", "options": ["Hemingway", "Fitzgerald", "Steinbeck", "Faulkner"], "answer": 1},
    {"q": "Who painted 'The Persistence of Memory'?", "options": ["Dalí", "Picasso", "Miró", "Kahlo"], "answer": 0},
    {"q": "Who wrote 'The Hobbit'?", "options": ["Lewis", "Tolkien", "Rowling", "Martin"], "answer": 1},
    {"q": "Who wrote 'To Kill a Mockingbird'?", "options": ["Lee", "Steinbeck", "Twain", "Morrison"], "answer": 0},
    {"q": "Who composed the 'Moonlight Sonata'?", "options": ["Mozart", "Beethoven", "Bach", "Chopin"], "answer": 1},
    {"q": "Who wrote 'The Catcher in the Rye'?", "options": ["Salinger", "Kerouac", "Vonnegut", "Heller"], "answer": 0},
    {"q": "Who painted the Sistine Chapel ceiling?", "options": ["Da Vinci", "Michelangelo", "Raphael", "Botticelli"], "answer": 1},
    {"q": "Who wrote 'Frankenstein'?", "options": ["Stoker", "Shelley", "Poe", "Wilde"], "answer": 1},

    # ── Sports ────────────────────────────────────────────────────────────────
    {"q": "How many players are on a soccer team on the field?", "options": ["9", "10", "11", "12"], "answer": 2},
    {"q": "In which sport is the Stanley Cup awarded?", "options": ["Baseball", "Hockey", "Basketball", "Football"], "answer": 1},
    {"q": "How many rings are on the Olympic flag?", "options": ["4", "5", "6", "7"], "answer": 1},
    {"q": "In tennis, what is a score of zero called?", "options": ["Nil", "Love", "Zero", "Blank"], "answer": 1},
    {"q": "Which country won the 2018 FIFA World Cup?", "options": ["Brazil", "Germany", "France", "Argentina"], "answer": 2},
    {"q": "How many holes are on a standard golf course?", "options": ["9", "12", "18", "24"], "answer": 2},
    {"q": "In basketball, how many points is a free throw?", "options": ["1", "2", "3", "4"], "answer": 0},
    {"q": "Which sport uses a shuttlecock?", "options": ["Tennis", "Squash", "Badminton", "Cricket"], "answer": 2},
    {"q": "How long is a marathon (km)?", "options": ["21.1", "42.195", "50", "100"], "answer": 1},
    {"q": "In which country did cricket originate?", "options": ["India", "Australia", "England", "Pakistan"], "answer": 2},
    {"q": "How many players on a basketball team on court?", "options": ["4", "5", "6", "7"], "answer": 1},
    {"q": "Which sport is played at Wimbledon?", "options": ["Cricket", "Tennis", "Golf", "Rugby"], "answer": 1},
    {"q": "In which country were the 2016 Summer Olympics held?", "options": ["China", "UK", "Brazil", "Russia"], "answer": 2},
    {"q": "What color jersey does the Tour de France leader wear?", "options": ["Green", "Yellow", "Polka dot", "White"], "answer": 1},
    {"q": "How many bases are on a baseball diamond?", "options": ["3", "4", "5", "6"], "answer": 1},

    # ── Technology & Gaming ───────────────────────────────────────────────────
    {"q": "What does CPU stand for?", "options": [
        "Central Processing Unit", "Computer Personal Unit",
        "Central Program Utility", "Core Processing Unit",
    ], "answer": 0},
    {"q": "Which game features a character named Steve?", "options": ["Fortnite", "Minecraft", "Roblox", "Terraria"], "answer": 1},
    {"q": "How many bytes are in a kilobyte (standard)?", "options": ["100", "512", "1000", "1024"], "answer": 3},
    {"q": "What does HTML stand for?", "options": [
        "Hyper Text Markup Language", "High Tech Modern Language",
        "Home Tool Markup Language", "Hyper Transfer Mark Language",
    ], "answer": 0},
    {"q": "Who founded Microsoft?", "options": ["Jobs", "Gates", "Zuckerberg", "Musk"], "answer": 1},
    {"q": "What year was the first iPhone released?", "options": ["2005", "2007", "2009", "2010"], "answer": 1},
    {"q": "What does USB stand for?", "options": [
        "Universal Serial Bus", "Unified System Bus",
        "Universal System Bridge", "Unit Serial Buffer",
    ], "answer": 0},
    {"q": "Which company makes PlayStation?", "options": ["Microsoft", "Nintendo", "Sony", "Sega"], "answer": 2},
    {"q": "What programming language is known for its snake logo?", "options": ["Java", "Python", "Ruby", "C++"], "answer": 1},
    {"q": "What does GPU stand for?", "options": [
        "Graphics Processing Unit", "General Processing Utility",
        "Global Program Unit", "Graphic Power Upgrade",
    ], "answer": 0},
    {"q": "Which game has characters called Creepers?", "options": ["Terraria", "Minecraft", "Fortnite", "Roblox"], "answer": 1},
    {"q": "What does Wi-Fi stand for (commonly)?", "options": [
        "Wireless Fidelity", "Wide Frequency", "Wired Fiber", "Web Interface",
    ], "answer": 0},
    {"q": "Who is the creator of Facebook?", "options": ["Musk", "Bezos", "Zuckerberg", "Gates"], "answer": 2},
    {"q": "What year was Minecraft officially released?", "options": ["2009", "2011", "2013", "2015"], "answer": 1},
    {"q": "What does RAM stand for?", "options": [
        "Random Access Memory", "Read Access Memory",
        "Run Active Memory", "Rapid Application Module",
    ], "answer": 0},
    {"q": "Which company owns Android?", "options": ["Apple", "Microsoft", "Google", "Samsung"], "answer": 2},
    {"q": "What is the name of Mario's brother?", "options": ["Wario", "Luigi", "Toad", "Yoshi"], "answer": 1},
    {"q": "What does AI stand for?", "options": [
        "Automated Intelligence", "Artificial Intelligence",
        "Advanced Integration", "Applied Informatics",
    ], "answer": 1},
    {"q": "Which game popularized the battle royale genre?", "options": ["Apex", "Fortnite", "PUBG", "Warzone"], "answer": 2},
    {"q": "What does URL stand for?", "options": [
        "Uniform Resource Locator", "Universal Reference Link",
        "Unified Resource Library", "User Resource Locator",
    ], "answer": 0},

    # ── Movies & TV ───────────────────────────────────────────────────────────
    {"q": "Who directed 'Jurassic Park'?", "options": ["Lucas", "Spielberg", "Cameron", "Nolan"], "answer": 1},
    {"q": "What is the highest-grossing film of all time (unadjusted)?", "options": ["Endgame", "Avatar", "Titanic", "Star Wars"], "answer": 1},
    {"q": "Which movie features the quote 'May the Force be with you'?", "options": ["Star Trek", "Star Wars", "Dune", "Guardians"], "answer": 1},
    {"q": "Who played Jack in 'Titanic'?", "options": ["Pitt", "DiCaprio", "Cruise", "Depp"], "answer": 1},
    {"q": "What is the name of the wizard school in Harry Potter?", "options": ["Durmstrang", "Hogwarts", "Beauxbatons", "Ilvermorny"], "answer": 1},
    {"q": "Which animated film features Elsa?", "options": ["Tangled", "Frozen", "Moana", "Brave"], "answer": 1},
    {"q": "Who directed 'The Dark Knight'?", "options": ["Spielberg", "Nolan", "Scorsese", "Tarantino"], "answer": 1},
    {"q": "What is the name of the toy cowboy in Toy Story?", "options": ["Buzz", "Woody", "Rex", "Slinky"], "answer": 1},
    {"q": "Which series features Walter White?", "options": ["The Wire", "Breaking Bad", "Sopranos", "Ozark"], "answer": 1},
    {"q": "What animal is Simba in 'The Lion King'?", "options": ["Tiger", "Lion", "Leopard", "Cheetah"], "answer": 1},
    {"q": "Who played Iron Man in the MCU?", "options": ["Evans", "Downey Jr.", "Hemsworth", "Pratt"], "answer": 1},
    {"q": "What is the name of the kingdom in 'Black Panther'?", "options": ["Zamunda", "Wakanda", "Genovia", "Latveria"], "answer": 1},
    {"q": "Which movie features a DeLorean time machine?", "options": ["Terminator", "Back to the Future", "Looper", "Interstellar"], "answer": 1},
    {"q": "Who voices Shrek?", "options": ["Farrell", "Myers", "Murphy", "Rock"], "answer": 1},
    {"q": "What is the name of the pirate in 'Pirates of the Caribbean'?", "options": ["Hook", "Sparrow", "Silver", "Flint"], "answer": 1},

    # ── Music ─────────────────────────────────────────────────────────────────
    {"q": "Who is known as the 'King of Pop'?", "options": ["Elvis", "Jackson", "Prince", "Brown"], "answer": 1},
    {"q": "Which band sang 'Bohemian Rhapsody'?", "options": ["Beatles", "Queen", "Led Zeppelin", "Pink Floyd"], "answer": 1},
    {"q": "What instrument has 88 keys?", "options": ["Guitar", "Piano", "Violin", "Flute"], "answer": 1},
    {"q": "Who sang 'Shape of You'?", "options": ["Sheeran", "Bieber", "Styles", "Mendes"], "answer": 0},
    {"q": "Which country is K-pop most associated with?", "options": ["Japan", "China", "South Korea", "Thailand"], "answer": 2},
    {"q": "How many strings does a standard guitar have?", "options": ["4", "5", "6", "7"], "answer": 2},
    {"q": "Who composed 'The Four Seasons'?", "options": ["Bach", "Vivaldi", "Mozart", "Handel"], "answer": 1},
    {"q": "Which artist released the album 'Thriller'?", "options": ["Prince", "Jackson", "Madonna", "Wonder"], "answer": 1},
    {"q": "What genre is Beethoven most associated with?", "options": ["Jazz", "Classical", "Rock", "Blues"], "answer": 1},
    {"q": "Who sang 'Rolling in the Deep'?", "options": ["Adele", "Beyoncé", "Rihanna", "Perry"], "answer": 0},

    # ── Food & Nature ─────────────────────────────────────────────────────────
    {"q": "What fruit is known for keeping doctors away?", "options": ["Banana", "Apple", "Orange", "Grape"], "answer": 1},
    {"q": "What is sushi traditionally wrapped in?", "options": ["Lettuce", "Nori", "Rice paper", "Tortilla"], "answer": 1},
    {"q": "Which nut is used to make marzipan?", "options": ["Walnut", "Almond", "Peanut", "Cashew"], "answer": 1},
    {"q": "What is the main ingredient in guacamole?", "options": ["Tomato", "Avocado", "Pepper", "Onion"], "answer": 1},
    {"q": "Which animal is the tallest in the world?", "options": ["Elephant", "Giraffe", "Ostrich", "Camel"], "answer": 1},
    {"q": "What is a group of lions called?", "options": ["Pack", "Herd", "Pride", "Flock"], "answer": 2},
    {"q": "Which bird is a symbol of peace?", "options": ["Eagle", "Dove", "Owl", "Swan"], "answer": 1},
    {"q": "What spice comes from dried bark?", "options": ["Pepper", "Cinnamon", "Cumin", "Paprika"], "answer": 1},
    {"q": "Which planet is known as Earth's twin?", "options": ["Mars", "Venus", "Mercury", "Jupiter"], "answer": 1},
    {"q": "What is the fastest land animal?", "options": ["Lion", "Cheetah", "Horse", "Antelope"], "answer": 1},
    {"q": "Which fish is Nemo in 'Finding Nemo'?", "options": ["Goldfish", "Clownfish", "Angelfish", "Betta"], "answer": 1},
    {"q": "What tree produces acorns?", "options": ["Maple", "Oak", "Pine", "Birch"], "answer": 1},
    {"q": "Which vitamin is abundant in citrus fruits?", "options": ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], "answer": 2},
    {"q": "What is the national animal of Australia?", "options": ["Koala", "Kangaroo", "Platypus", "Emu"], "answer": 1},
    {"q": "Which bee product is used as a sweetener?", "options": ["Wax", "Honey", "Pollen", "Royal jelly"], "answer": 1},

    # ── General Knowledge ─────────────────────────────────────────────────────
    {"q": "How many days are in a leap year?", "options": ["364", "365", "366", "367"], "answer": 2},
    {"q": "What is the most spoken language in the world?", "options": ["English", "Spanish", "Mandarin", "Hindi"], "answer": 2},
    {"q": "What color do you get mixing red and blue?", "options": ["Green", "Purple", "Orange", "Brown"], "answer": 1},
    {"q": "How many hours are in a day?", "options": ["12", "24", "48", "36"], "answer": 1},
    {"q": "What is the currency of the United Kingdom?", "options": ["Euro", "Dollar", "Pound", "Franc"], "answer": 2},
    {"q": "What is the currency of Japan?", "options": ["Won", "Yuan", "Yen", "Ringgit"], "answer": 2},
    {"q": "How many letters in the English alphabet?", "options": ["24", "25", "26", "27"], "answer": 2},
    {"q": "What is the largest planet in our solar system?", "options": ["Saturn", "Jupiter", "Neptune", "Uranus"], "answer": 1},
    {"q": "What do bees collect from flowers?", "options": ["Water", "Pollen", "Seeds", "Leaves"], "answer": 1},
    {"q": "What is the freezing point of water (°C)?", "options": ["-1", "0", "1", "32"], "answer": 1},
    {"q": "How many weeks are in a year?", "options": ["48", "50", "52", "54"], "answer": 2},
    {"q": "What is the symbol for infinity?", "options": ["∞", "π", "∑", "Ω"], "answer": 0},
    {"q": "Which chess piece can only move diagonally?", "options": ["Rook", "Knight", "Bishop", "Queen"], "answer": 2},
    {"q": "What is the hardest rock type?", "options": ["Granite", "Marble", "Diamond", "Quartzite"], "answer": 2},
    {"q": "How many stars are on the US flag?", "options": ["48", "50", "52", "13"], "answer": 1},
    {"q": "What is the national sport of Canada?", "options": ["Football", "Hockey", "Lacrosse", "Baseball"], "answer": 2},
    {"q": "What does SOS stand for (traditionally)?", "options": [
        "Save Our Ship", "Send Our Signal", "Survivors On Shore", "It's not an acronym",
    ], "answer": 3},
    {"q": "Which planet is known for the Great Red Spot?", "options": ["Mars", "Saturn", "Jupiter", "Neptune"], "answer": 2},
    {"q": "What is the main ingredient in bread?", "options": ["Rice", "Flour", "Corn", "Oats"], "answer": 1},
    {"q": "How many minutes in an hour?", "options": ["30", "45", "60", "100"], "answer": 2},
]
